### ISSUE TITLE
remove required fields from outbound integration

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-cashcall#22]
The question has come up in [ticket 8467](https://activeprospect.zendesk.com/agent/tickets/8467) about the outbound integration to Prime being skipped when phone, or address, isn't available. 

I'm not sure why anything is "required" or validated for in this outbound integration, as its main purpose is to rebuild the XML for the lead received on the inbound side. Perhaps just because it's standard practice in most integrations. But rather than add logic to use a different phone number to pass these rules, etc., I think we can remove those requirements entirely. 

What do you think, @alexj?

**Comment by alexj** [comment]
I agree. Rereading the thread, Min indicates that there will be instances where it is perfectly acceptable and expected that one or more of those values won't be sent. Any required logic can be handled in mappings where appropriate, which would make more sense anyway, as the same phone number/address should be used for data appends.
